# The URL the site will be built for
base_url = "https://martin.noblia.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "after-dark-suizo"

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

# TODO(elsuizo:2021-08-06): encontre un colorscheme que no esta tan mal, pero cuando se pueda poner uno custom lo cambiamos
[markdown]
highlight_code = true
# highlight_theme = "gray-matter-dark"
highlight_theme = "nyx-bold"
# highlight_theme = "Tomorrow"
# highlight_theme = "boron"

[extra]
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://github.com/elsuizo", name = "Martin Noblia github"},
]
